# Generated by Django 5.1.1 on 2024-12-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0004_alter_student_options_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=10)),
            ],
        ),
    ]
