# Generated by Django 5.1.1 on 2025-01-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autori',
                'ordering': ['nazov'],
            },
        ),
        migrations.CreateModel(
            name='Miesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Miesto',
                'verbose_name_plural': 'Miesta',
                'ordering': ['nazov'],
            },
        ),
        migrations.CreateModel(
            name='Vydavatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Vydavatel',
                'verbose_name_plural': 'Vydavatelia',
                'ordering': ['nazov'],
            },
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=20)),
                ('rok', models.IntegerField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kniznica.autor')),
                ('miesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kniznica.miesto')),
                ('vydavatel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kniznica.vydavatel')),
            ],
            options={
                'verbose_name': 'Kniha',
                'verbose_name_plural': 'Knihy',
                'ordering': ['nazov'],
            },
        ),
    ]
