# Generated by Django 5.1.1 on 2025-01-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kniznica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['priezvisko'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autori'},
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nazov',
            new_name='meno',
        ),
        migrations.AddField(
            model_name='autor',
            name='priezvisko',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
