# Generated by Django 5.1.2 on 2025-01-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autori',
                'ordering': ['priezvisko'],
            },
        ),
        migrations.CreateModel(
            name='Vydavatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Vydavatel',
                'verbose_name_plural': 'Vydavatelia',
                'ordering': ['nazov'],
            },
        ),
    ]
