# Generated by Django 5.1.2 on 2025-01-21 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kniznica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Miesto',
                'verbose_name_plural': 'Miesta',
                'ordering': ['nazov'],
            },
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=30)),
                ('rok', models.IntegerField(max_length=10)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kniznica.autor')),
                ('vydavatel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kniznica.vydavatel')),
                ('miesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kniznica.miesto')),
            ],
            options={
                'verbose_name': 'Kniha',
                'verbose_name_plural': 'Knihy',
                'ordering': ['nazov'],
            },
        ),
    ]
