# Generated by Django 5.1.2 on 2025-01-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kniznica', '0002_miesto_kniha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kniha',
            name='rok',
            field=models.IntegerField(),
        ),
    ]
